import 'dart:io';

import 'models.dart';
import 'scanner_android.dart' as android;
import 'scanner_core.dart';
import 'scanner_ios.dart' as ios;
import 'scanner_linux.dart' as linux;
import 'scanner_macos.dart' as macos;
import 'scanner_windows.dart' as windows;
import 'scanner_constants.dart';

export 'scanner_core.dart' show ProgressCallback, HostUpdateCallback;

class LanScanner {
  LanScanner._(this._impl);

  factory LanScanner({
    int maxHostsPerInterface = ScannerDefaults.maxHostsPerInterface,
    int parallelRequests = ScannerDefaults.parallelRequests,
    Duration pingTimeout = ScannerDefaults.pingTimeout,
    Duration mdnsListenWindow = ScannerDefaults.mdnsListenWindow,
    bool enableMdns = ScannerDefaults.enableMdns,
    bool enableNbns = ScannerDefaults.enableNbns,
    bool enableReverseDns = ScannerDefaults.enableReverseDns,
    double timeoutFactor = ScannerDefaults.timeoutFactor,
    bool enableIpv6Ping = ScannerDefaults.enableIpv6Ping,
    bool enableSsdp = ScannerDefaults.enableSsdp,
    bool enableNbnsBroadcast = ScannerDefaults.enableNbnsBroadcast,
    bool enableTlsHostnames = ScannerDefaults.enableTlsHostnames,
    bool enableWsDiscovery = ScannerDefaults.enableWsDiscovery,
    bool enableLlmnr = ScannerDefaults.enableLlmnr,
    bool enableMdnsReverse = ScannerDefaults.enableMdnsReverse,
    bool enableSshBanner = ScannerDefaults.enableSshBanner,
    bool enableTelnetBanner = ScannerDefaults.enableTelnetBanner,
    bool enableSmb1 = ScannerDefaults.enableSmb1,
    bool enableDnsSearchDomain = ScannerDefaults.enableDnsSearchDomain,
    bool enableSnmpNames = ScannerDefaults.enableSnmpNames,
    bool enableSmbNames = ScannerDefaults.enableSmbNames,
    bool includeAdvancedHostnames = ScannerDefaults.includeAdvancedHostnames,
    bool debugTiming = ScannerDefaults.debugTiming,
    bool enableArpCache = ScannerDefaults.enableArpCache,
    bool enableNdp = ScannerDefaults.enableNdp,
    bool enableIpv6Discovery = ScannerDefaults.enableIpv6Discovery,
    bool enableHttpScan = ScannerDefaults.enableHttpScan,
    bool deferHttpScan = ScannerDefaults.deferHttpScan,
    bool allowReverseDnsFailure = ScannerDefaults.allowReverseDnsFailure,
    bool allowPingFailure = ScannerDefaults.allowPingFailure,
    bool enableTcpReachability = ScannerDefaults.enableTcpReachability,
    int? reverseDnsTimeoutMs,
    bool requireReverseDnsForProbes = ScannerDefaults.requireReverseDnsForProbes,
    List<String> preferredInterfaceNames = ScannerDefaults.preferredInterfaceNames,
  }) {
    if (Platform.isIOS) {
      return LanScanner._(ios.LanScanner(
        maxHostsPerInterface: maxHostsPerInterface,
        parallelRequests: parallelRequests,
        pingTimeout: pingTimeout,
        mdnsListenWindow: mdnsListenWindow,
        enableMdns: enableMdns,
        enableReverseDns: enableReverseDns,
        timeoutFactor: timeoutFactor,
        enableSsdp: enableSsdp,
        includeAdvancedHostnames: includeAdvancedHostnames,
        debugTiming: debugTiming,
        enableHttpScan: enableHttpScan,
        deferHttpScan: deferHttpScan,
        allowReverseDnsFailure: allowReverseDnsFailure,
        allowPingFailure: allowPingFailure,
        enableTcpReachability: enableTcpReachability,
        reverseDnsTimeoutMs: reverseDnsTimeoutMs,
        requireReverseDnsForProbes: requireReverseDnsForProbes,
        preferredInterfaceNames: preferredInterfaceNames,
      ));
    }
    if (Platform.isAndroid) {
      return LanScanner._(android.LanScanner(
        maxHostsPerInterface: maxHostsPerInterface,
        parallelRequests: parallelRequests,
        pingTimeout: pingTimeout,
        mdnsListenWindow: mdnsListenWindow,
        enableMdns: enableMdns,
        enableNbns: enableNbns,
        enableReverseDns: enableReverseDns,
        timeoutFactor: timeoutFactor,
        enableIpv6Ping: enableIpv6Ping,
        enableSsdp: enableSsdp,
        enableNbnsBroadcast: enableNbnsBroadcast,
        enableTlsHostnames: enableTlsHostnames,
        enableWsDiscovery: enableWsDiscovery,
        enableLlmnr: enableLlmnr,
        enableMdnsReverse: enableMdnsReverse,
        enableSshBanner: enableSshBanner,
        enableTelnetBanner: enableTelnetBanner,
        enableSmb1: enableSmb1,
        enableDnsSearchDomain: enableDnsSearchDomain,
        enableSnmpNames: enableSnmpNames,
        enableSmbNames: enableSmbNames,
        includeAdvancedHostnames: includeAdvancedHostnames,
        debugTiming: debugTiming,
        enableArpCache: enableArpCache,
        enableNdp: enableNdp,
        enableIpv6Discovery: enableIpv6Discovery,
        enableHttpScan: enableHttpScan,
        deferHttpScan: deferHttpScan,
        allowReverseDnsFailure: allowReverseDnsFailure,
        allowPingFailure: allowPingFailure,
        enableTcpReachability: enableTcpReachability,
        reverseDnsTimeoutMs: reverseDnsTimeoutMs,
        requireReverseDnsForProbes: requireReverseDnsForProbes,
        preferredInterfaceNames: preferredInterfaceNames,
      ));
    }
    if (Platform.isMacOS) {
      return LanScanner._(macos.LanScanner(
        maxHostsPerInterface: maxHostsPerInterface,
        parallelRequests: parallelRequests,
        pingTimeout: pingTimeout,
        mdnsListenWindow: mdnsListenWindow,
        enableMdns: enableMdns,
        enableNbns: enableNbns,
        enableReverseDns: enableReverseDns,
        timeoutFactor: timeoutFactor,
        enableIpv6Ping: enableIpv6Ping,
        enableSsdp: enableSsdp,
        enableNbnsBroadcast: enableNbnsBroadcast,
        enableTlsHostnames: enableTlsHostnames,
        enableWsDiscovery: enableWsDiscovery,
        enableLlmnr: enableLlmnr,
        enableMdnsReverse: enableMdnsReverse,
        enableSshBanner: enableSshBanner,
        enableTelnetBanner: enableTelnetBanner,
        enableSmb1: enableSmb1,
        enableDnsSearchDomain: enableDnsSearchDomain,
        enableSnmpNames: enableSnmpNames,
        enableSmbNames: enableSmbNames,
        includeAdvancedHostnames: includeAdvancedHostnames,
        debugTiming: debugTiming,
        enableArpCache: enableArpCache,
        enableNdp: enableNdp,
        enableIpv6Discovery: enableIpv6Discovery,
        enableHttpScan: enableHttpScan,
        deferHttpScan: deferHttpScan,
        allowReverseDnsFailure: allowReverseDnsFailure,
        allowPingFailure: allowPingFailure,
        enableTcpReachability: enableTcpReachability,
        reverseDnsTimeoutMs: reverseDnsTimeoutMs,
        requireReverseDnsForProbes: requireReverseDnsForProbes,
        preferredInterfaceNames: preferredInterfaceNames,
      ));
    }
    if (Platform.isLinux) {
      return LanScanner._(linux.LanScanner(
        maxHostsPerInterface: maxHostsPerInterface,
        parallelRequests: parallelRequests,
        pingTimeout: pingTimeout,
        mdnsListenWindow: mdnsListenWindow,
        enableMdns: enableMdns,
        enableNbns: enableNbns,
        enableReverseDns: enableReverseDns,
        timeoutFactor: timeoutFactor,
        enableIpv6Ping: enableIpv6Ping,
        enableSsdp: enableSsdp,
        enableNbnsBroadcast: enableNbnsBroadcast,
        enableTlsHostnames: enableTlsHostnames,
        enableWsDiscovery: enableWsDiscovery,
        enableLlmnr: enableLlmnr,
        enableMdnsReverse: enableMdnsReverse,
        enableSshBanner: enableSshBanner,
        enableTelnetBanner: enableTelnetBanner,
        enableSmb1: enableSmb1,
        enableDnsSearchDomain: enableDnsSearchDomain,
        enableSnmpNames: enableSnmpNames,
        enableSmbNames: enableSmbNames,
        includeAdvancedHostnames: includeAdvancedHostnames,
        debugTiming: debugTiming,
        enableArpCache: enableArpCache,
        enableNdp: enableNdp,
        enableIpv6Discovery: enableIpv6Discovery,
        enableHttpScan: enableHttpScan,
        deferHttpScan: deferHttpScan,
        allowReverseDnsFailure: allowReverseDnsFailure,
        allowPingFailure: allowPingFailure,
        enableTcpReachability: enableTcpReachability,
        reverseDnsTimeoutMs: reverseDnsTimeoutMs,
        requireReverseDnsForProbes: requireReverseDnsForProbes,
        preferredInterfaceNames: preferredInterfaceNames,
      ));
    }
    return LanScanner._(windows.LanScanner(
      maxHostsPerInterface: maxHostsPerInterface,
      parallelRequests: parallelRequests,
      pingTimeout: pingTimeout,
      mdnsListenWindow: mdnsListenWindow,
      enableMdns: enableMdns,
      enableNbns: enableNbns,
      enableReverseDns: enableReverseDns,
      timeoutFactor: timeoutFactor,
      enableIpv6Ping: enableIpv6Ping,
      enableSsdp: enableSsdp,
      enableNbnsBroadcast: enableNbnsBroadcast,
      enableTlsHostnames: enableTlsHostnames,
      enableWsDiscovery: enableWsDiscovery,
      enableLlmnr: enableLlmnr,
      enableMdnsReverse: enableMdnsReverse,
      enableSshBanner: enableSshBanner,
      enableTelnetBanner: enableTelnetBanner,
      enableSmb1: enableSmb1,
      enableDnsSearchDomain: enableDnsSearchDomain,
      enableSnmpNames: enableSnmpNames,
      enableSmbNames: enableSmbNames,
      includeAdvancedHostnames: includeAdvancedHostnames,
      debugTiming: debugTiming,
      enableArpCache: enableArpCache,
      enableNdp: enableNdp,
      enableIpv6Discovery: enableIpv6Discovery,
      enableHttpScan: enableHttpScan,
      deferHttpScan: deferHttpScan,
      allowReverseDnsFailure: allowReverseDnsFailure,
      allowPingFailure: allowPingFailure,
      enableTcpReachability: enableTcpReachability,
      reverseDnsTimeoutMs: reverseDnsTimeoutMs,
      requireReverseDnsForProbes: requireReverseDnsForProbes,
      preferredInterfaceNames: preferredInterfaceNames,
    ));
  }

  final LanScannerCore _impl;

  Future<List<DiscoveredHost>> scan({
    ProgressCallback? onProgress,
    HostUpdateCallback? onHost,
  }) {
    return _impl.scan(onProgress: onProgress, onHost: onHost);
  }
}
